apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-opencluster
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: opencluster
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
    {{- if .Values.relay.enabled }}
    - name: relay-tls
      port: {{ .Values.relay.externalPort }}
      targetPort: relay-tls
    {{- end }}
