LOCK TABLE organization, organization_membership, operator_session, relay_registration IN ACCESS EXCLUSIVE MODE;

DROP TRIGGER organization_identity_is_immutable ON organization;
DROP FUNCTION prevent_organization_identity_retargeting();

DROP TRIGGER alert_event_organization_id_is_resolved ON alert_event;
DROP TRIGGER audit_event_organization_id_is_resolved ON audit_event;
DROP TRIGGER change_ledger_organization_id_is_resolved ON change_ledger;
DROP TRIGGER change_ledger_scope_organization_id_is_resolved ON change_ledger_scope;
DROP TRIGGER conversation_organization_id_is_resolved ON conversation;
DROP TRIGGER conversation_message_organization_id_is_resolved ON conversation_message;
DROP TRIGGER deployment_sign_in_flow_organization_id_is_resolved ON deployment_sign_in_flow;
DROP TRIGGER incident_organization_id_is_resolved ON incident;
DROP TRIGGER integration_organization_id_is_resolved ON integration;
DROP TRIGGER integration_connect_flow_organization_id_is_resolved ON integration_connect_flow;
DROP TRIGGER integration_delivery_organization_id_is_resolved ON integration_delivery;
DROP TRIGGER integration_installation_organization_id_is_resolved ON integration_installation;
DROP TRIGGER investigation_organization_id_is_resolved ON investigation;
DROP TRIGGER investigation_event_organization_id_is_resolved ON investigation_event;
DROP TRIGGER investigation_tool_run_organization_id_is_resolved ON investigation_tool_run;
DROP TRIGGER operator_session_organization_id_is_resolved ON operator_session;
DROP TRIGGER organization_membership_organization_id_is_resolved ON organization_membership;
DROP TRIGGER postmortem_organization_id_is_resolved ON postmortem;
DROP TRIGGER relay_bootstrap_token_organization_id_is_resolved ON relay_bootstrap_token;
DROP TRIGGER relay_job_organization_id_is_resolved ON relay_job;
DROP TRIGGER relay_registration_organization_id_is_resolved ON relay_registration;
DROP TRIGGER relay_session_conflict_event_organization_id_is_resolved ON relay_session_conflict_event;
DROP TRIGGER slack_conversation_organization_id_is_resolved ON slack_conversation;
DROP TRIGGER slack_reply_organization_id_is_resolved ON slack_reply;
DROP TRIGGER webhook_work_organization_id_is_resolved ON webhook_work;
DROP FUNCTION resolve_tenant_organization_id();

ALTER TABLE audit_event DROP CONSTRAINT audit_event_scope_is_whole;
ALTER TABLE operator_session DROP CONSTRAINT operator_session_scope_is_whole;

ALTER TABLE alert_event DROP CONSTRAINT alert_event_integration_is_in_the_same_org;
ALTER TABLE change_ledger DROP CONSTRAINT change_ledger_integration_is_in_the_org;
ALTER TABLE change_ledger_scope DROP CONSTRAINT change_ledger_scope_integration_is_in_the_org;
ALTER TABLE conversation DROP CONSTRAINT conversation_incident_is_in_the_same_org;
ALTER TABLE conversation_message DROP CONSTRAINT conversation_message_belongs_to_its_conversation;
ALTER TABLE conversation_message DROP CONSTRAINT conversation_message_names_an_org_investigation;
ALTER TABLE incident DROP CONSTRAINT incident_integration_is_in_the_same_org;
ALTER TABLE integration_delivery DROP CONSTRAINT integration_delivery_is_in_the_same_org;
ALTER TABLE integration_installation DROP CONSTRAINT integration_installation_matches_parent_kind;
ALTER TABLE integration DROP CONSTRAINT integration_relay_is_in_the_same_org;
ALTER TABLE investigation DROP CONSTRAINT investigation_conversation_is_in_the_same_org;
ALTER TABLE investigation_event DROP CONSTRAINT investigation_event_belongs_to_its_investigation;
ALTER TABLE investigation DROP CONSTRAINT investigation_incident_is_in_the_same_org;
ALTER TABLE investigation_tool_run DROP CONSTRAINT investigation_tool_run_belongs_to_its_investigation;
ALTER TABLE investigation_tool_run DROP CONSTRAINT investigation_tool_run_names_an_org_integration;
ALTER TABLE investigation DROP CONSTRAINT investigation_webhook_work_is_in_the_same_org;
ALTER TABLE postmortem DROP CONSTRAINT postmortem_incident_is_in_the_same_org;
ALTER TABLE relay_job DROP CONSTRAINT relay_job_integration_is_in_the_same_org;
ALTER TABLE relay_job DROP CONSTRAINT relay_job_investigation_belongs_to_organization;
ALTER TABLE relay_job DROP CONSTRAINT relay_job_relay_is_in_the_same_org;
ALTER TABLE slack_conversation DROP CONSTRAINT slack_conversation_integration_is_in_the_same_org;
ALTER TABLE slack_conversation DROP CONSTRAINT slack_conversation_is_in_the_same_org;
ALTER TABLE slack_reply DROP CONSTRAINT slack_reply_names_its_mapping;
ALTER TABLE slack_reply DROP CONSTRAINT slack_reply_names_its_conversation_investigation;
ALTER TABLE webhook_work DROP CONSTRAINT webhook_work_delivery_is_in_the_same_org;
ALTER TABLE webhook_work DROP CONSTRAINT webhook_work_incident_is_in_the_same_org;
ALTER TABLE webhook_work DROP CONSTRAINT webhook_work_integration_is_in_the_same_org;
ALTER TABLE webhook_work DROP CONSTRAINT webhook_work_message_is_in_the_same_org;

ALTER TABLE alert_event DROP CONSTRAINT alert_event_org_id_check;
ALTER TABLE audit_event DROP CONSTRAINT audit_event_org_id_check;
ALTER TABLE change_ledger DROP CONSTRAINT change_ledger_org_id_check;
ALTER TABLE change_ledger_scope DROP CONSTRAINT change_ledger_scope_org_id_check;
ALTER TABLE conversation DROP CONSTRAINT conversation_org_id_check;
ALTER TABLE conversation_message DROP CONSTRAINT conversation_message_org_id_check;
ALTER TABLE incident DROP CONSTRAINT incident_org_id_check;
ALTER TABLE integration DROP CONSTRAINT integration_org_id_check;
ALTER TABLE integration_connect_flow DROP CONSTRAINT integration_connect_flow_org_id_check;
ALTER TABLE integration_delivery DROP CONSTRAINT integration_delivery_org_id_check;
ALTER TABLE integration_installation DROP CONSTRAINT integration_installation_org_id_check;
ALTER TABLE investigation DROP CONSTRAINT investigation_org_id_check;
ALTER TABLE investigation_event DROP CONSTRAINT investigation_event_org_id_check;
ALTER TABLE investigation_tool_run DROP CONSTRAINT investigation_tool_run_org_id_check;
ALTER TABLE operator_session DROP CONSTRAINT operator_session_org_id_check;
ALTER TABLE organization DROP CONSTRAINT organization_org_id_check;
ALTER TABLE organization_membership DROP CONSTRAINT organization_membership_org_id_check;
ALTER TABLE postmortem DROP CONSTRAINT postmortem_org_id_check;
ALTER TABLE relay_bootstrap_token DROP CONSTRAINT relay_bootstrap_token_org_id_check;
ALTER TABLE relay_job DROP CONSTRAINT relay_job_org_id_check;
ALTER TABLE relay_registration DROP CONSTRAINT relay_registration_org_id_check;
ALTER TABLE relay_session_conflict_event DROP CONSTRAINT relay_session_conflict_event_org_id_check;
ALTER TABLE slack_conversation DROP CONSTRAINT slack_conversation_org_id_check;
ALTER TABLE slack_reply DROP CONSTRAINT slack_reply_org_id_check;
ALTER TABLE webhook_work DROP CONSTRAINT webhook_work_org_id_check;

ALTER TABLE organization ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE organization ALTER COLUMN org_id SET DEFAULT gen_random_uuid();
ALTER TABLE organization ALTER COLUMN audit_retention_days SET DEFAULT 90;
ALTER TABLE alert_event ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE audit_event ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE change_ledger ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE change_ledger_scope ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE conversation ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE conversation_message ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE deployment_sign_in_flow ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE incident ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE integration ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE integration_connect_flow ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE integration_delivery ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE integration_installation ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE investigation ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE investigation_event ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE investigation_tool_run ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE operator_session ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE organization_membership ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE postmortem ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE relay_bootstrap_token ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE relay_job ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE relay_registration ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE relay_session_conflict_event ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE slack_conversation ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE slack_reply ALTER COLUMN org_id TYPE uuid USING organization_id;
ALTER TABLE webhook_work ALTER COLUMN org_id TYPE uuid USING organization_id;

ALTER TABLE alert_event DROP COLUMN organization_id;
ALTER TABLE audit_event DROP COLUMN organization_id;
ALTER TABLE change_ledger DROP COLUMN organization_id;
ALTER TABLE change_ledger_scope DROP COLUMN organization_id;
ALTER TABLE conversation DROP COLUMN organization_id;
ALTER TABLE conversation_message DROP COLUMN organization_id;
ALTER TABLE deployment_sign_in_flow DROP COLUMN organization_id;
ALTER TABLE incident DROP COLUMN organization_id;
ALTER TABLE integration DROP COLUMN organization_id;
ALTER TABLE integration_connect_flow DROP COLUMN organization_id;
ALTER TABLE integration_delivery DROP COLUMN organization_id;
ALTER TABLE integration_installation DROP COLUMN organization_id;
ALTER TABLE investigation DROP COLUMN organization_id;
ALTER TABLE investigation_event DROP COLUMN organization_id;
ALTER TABLE investigation_tool_run DROP COLUMN organization_id;
ALTER TABLE operator_session DROP COLUMN organization_id;
ALTER TABLE organization_membership DROP COLUMN organization_id;
ALTER TABLE postmortem DROP COLUMN organization_id;
ALTER TABLE relay_bootstrap_token DROP COLUMN organization_id;
ALTER TABLE relay_job DROP COLUMN organization_id;
ALTER TABLE relay_registration DROP COLUMN organization_id;
ALTER TABLE relay_session_conflict_event DROP COLUMN organization_id;
ALTER TABLE slack_conversation DROP COLUMN organization_id;
ALTER TABLE slack_reply DROP COLUMN organization_id;
ALTER TABLE webhook_work DROP COLUMN organization_id;
ALTER TABLE organization DROP COLUMN organization_id;

ALTER TABLE alert_event ADD CONSTRAINT alert_event_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE audit_event ADD CONSTRAINT audit_event_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE change_ledger ADD CONSTRAINT change_ledger_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE change_ledger_scope ADD CONSTRAINT change_ledger_scope_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE conversation ADD CONSTRAINT conversation_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE conversation_message ADD CONSTRAINT conversation_message_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE deployment_sign_in_flow ADD CONSTRAINT deployment_sign_in_flow_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE incident ADD CONSTRAINT incident_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE integration ADD CONSTRAINT integration_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE integration_connect_flow ADD CONSTRAINT integration_connect_flow_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE integration_delivery ADD CONSTRAINT integration_delivery_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE integration_installation ADD CONSTRAINT integration_installation_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE investigation ADD CONSTRAINT investigation_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE investigation_event ADD CONSTRAINT investigation_event_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE investigation_tool_run ADD CONSTRAINT investigation_tool_run_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE operator_session ADD CONSTRAINT operator_session_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE organization_membership ADD CONSTRAINT organization_membership_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE postmortem ADD CONSTRAINT postmortem_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE relay_bootstrap_token ADD CONSTRAINT relay_bootstrap_token_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE relay_job ADD CONSTRAINT relay_job_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE relay_registration ADD CONSTRAINT relay_registration_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE relay_session_conflict_event ADD CONSTRAINT relay_session_conflict_event_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE slack_conversation ADD CONSTRAINT slack_conversation_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE slack_reply ADD CONSTRAINT slack_reply_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;
ALTER TABLE webhook_work ADD CONSTRAINT webhook_work_organization_exists FOREIGN KEY (org_id) REFERENCES organization (org_id) ON DELETE RESTRICT;

ALTER TABLE alert_event ADD CONSTRAINT alert_event_integration_is_in_the_same_org FOREIGN KEY (org_id, integration_id) REFERENCES integration (org_id, integration_id);
ALTER TABLE change_ledger ADD CONSTRAINT change_ledger_integration_is_in_the_org FOREIGN KEY (org_id, integration_id) REFERENCES integration (org_id, integration_id);
ALTER TABLE change_ledger_scope ADD CONSTRAINT change_ledger_scope_integration_is_in_the_org FOREIGN KEY (org_id, integration_id) REFERENCES integration (org_id, integration_id);
ALTER TABLE conversation ADD CONSTRAINT conversation_incident_is_in_the_same_org FOREIGN KEY (org_id, incident_id) REFERENCES incident (org_id, incident_id);
ALTER TABLE conversation_message ADD CONSTRAINT conversation_message_belongs_to_its_conversation FOREIGN KEY (org_id, conversation_id) REFERENCES conversation (org_id, conversation_id) ON DELETE CASCADE;
ALTER TABLE conversation_message ADD CONSTRAINT conversation_message_names_an_org_investigation FOREIGN KEY (org_id, investigation_id) REFERENCES investigation (org_id, investigation_id);
ALTER TABLE incident ADD CONSTRAINT incident_integration_is_in_the_same_org FOREIGN KEY (org_id, integration_id) REFERENCES integration (org_id, integration_id);
ALTER TABLE integration_delivery ADD CONSTRAINT integration_delivery_is_in_the_same_org FOREIGN KEY (org_id, integration_id) REFERENCES integration (org_id, integration_id) ON DELETE CASCADE;
ALTER TABLE integration_installation ADD CONSTRAINT integration_installation_matches_parent_kind FOREIGN KEY (org_id, integration_id, integration_type_id) REFERENCES integration (org_id, integration_id, integration_type_id) ON DELETE CASCADE;
ALTER TABLE integration ADD CONSTRAINT integration_relay_is_in_the_same_org FOREIGN KEY (org_id, relay_id) REFERENCES relay_registration (org_id, registration_id);
ALTER TABLE investigation ADD CONSTRAINT investigation_conversation_is_in_the_same_org FOREIGN KEY (org_id, conversation_id) REFERENCES conversation (org_id, conversation_id);
ALTER TABLE investigation_event ADD CONSTRAINT investigation_event_belongs_to_its_investigation FOREIGN KEY (org_id, investigation_id) REFERENCES investigation (org_id, investigation_id) ON DELETE CASCADE;
ALTER TABLE investigation ADD CONSTRAINT investigation_incident_is_in_the_same_org FOREIGN KEY (org_id, incident_id) REFERENCES incident (org_id, incident_id);
ALTER TABLE investigation_tool_run ADD CONSTRAINT investigation_tool_run_belongs_to_its_investigation FOREIGN KEY (org_id, investigation_id) REFERENCES investigation (org_id, investigation_id) ON DELETE CASCADE;
ALTER TABLE investigation_tool_run ADD CONSTRAINT investigation_tool_run_names_an_org_integration FOREIGN KEY (org_id, integration_id) REFERENCES integration (org_id, integration_id);
ALTER TABLE investigation ADD CONSTRAINT investigation_webhook_work_is_in_the_same_org FOREIGN KEY (org_id, webhook_work_id) REFERENCES webhook_work (org_id, work_id);
ALTER TABLE postmortem ADD CONSTRAINT postmortem_incident_is_in_the_same_org FOREIGN KEY (org_id, incident_id) REFERENCES incident (org_id, incident_id);
ALTER TABLE relay_job ADD CONSTRAINT relay_job_integration_is_in_the_same_org FOREIGN KEY (org_id, integration_id) REFERENCES integration (org_id, integration_id);
ALTER TABLE relay_job ADD CONSTRAINT relay_job_investigation_belongs_to_organization FOREIGN KEY (org_id, investigation_id) REFERENCES investigation (org_id, investigation_id) ON DELETE CASCADE;
ALTER TABLE relay_job ADD CONSTRAINT relay_job_relay_is_in_the_same_org FOREIGN KEY (org_id, registration_id) REFERENCES relay_registration (org_id, registration_id);
ALTER TABLE slack_conversation ADD CONSTRAINT slack_conversation_integration_is_in_the_same_org FOREIGN KEY (org_id, integration_id) REFERENCES integration (org_id, integration_id) ON DELETE CASCADE;
ALTER TABLE slack_conversation ADD CONSTRAINT slack_conversation_is_in_the_same_org FOREIGN KEY (org_id, conversation_id) REFERENCES conversation (org_id, conversation_id) ON DELETE CASCADE;
ALTER TABLE slack_reply ADD CONSTRAINT slack_reply_names_its_mapping FOREIGN KEY (org_id, conversation_id) REFERENCES slack_conversation (org_id, conversation_id) ON DELETE RESTRICT;
ALTER TABLE slack_reply ADD CONSTRAINT slack_reply_names_its_conversation_investigation FOREIGN KEY (org_id, conversation_id, investigation_id) REFERENCES investigation (org_id, conversation_id, investigation_id) ON DELETE CASCADE;
ALTER TABLE webhook_work ADD CONSTRAINT webhook_work_delivery_is_in_the_same_org FOREIGN KEY (org_id, delivery_id) REFERENCES integration_delivery (org_id, delivery_id) ON DELETE CASCADE;
ALTER TABLE webhook_work ADD CONSTRAINT webhook_work_incident_is_in_the_same_org FOREIGN KEY (org_id, incident_id) REFERENCES incident (org_id, incident_id);
ALTER TABLE webhook_work ADD CONSTRAINT webhook_work_integration_is_in_the_same_org FOREIGN KEY (org_id, integration_id) REFERENCES integration (org_id, integration_id);
ALTER TABLE webhook_work ADD CONSTRAINT webhook_work_message_is_in_the_same_org FOREIGN KEY (org_id, conversation_id, message_sequence) REFERENCES conversation_message (org_id, conversation_id, sequence);
