package e2e

import (
	"context"
	"fmt"
	"time"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
)

// A scenario is a Kubernetes cluster broken in a known way, on purpose, with the cause written
// down before the system ever sees it.
//
// Declaring the cause first is the whole discipline. A conclusion compared against a truth
// written afterwards can always be rationalised into correctness, and an instrument that can be
// argued with is not an instrument.
//
// Every scenario is SYNTHETIC and contains no real data. That is a hard constraint rather than a
// convention: it is what makes a recorded model transcript safe to commit, and what lets this run
// against a cluster nobody has to audit first.

// Bounds on provisioning one scenario. A cluster that has not reached its declared broken state
// inside these is discarded loudly rather than scored — silently scoring a run of a different
// failure than the one declared is the worst thing this instrument could do, because it would
// corrupt the evidence being used to steer the product.
const (
	provisionTimeout = 4 * time.Minute
	readinessPoll    = 2 * time.Second
)

// Expectation is what a correct terminal outcome looks like for a scenario. It is part of ground
// truth and is never shown to a scorer.
type Expectation int

const (
	// ExpectExplanation means the evidence available is sufficient and a supported explanation is
	// the right answer.
	ExpectExplanation Expectation = iota + 1
	// ExpectCaveatedExplanation means an explanation is reachable but must carry a CoverageGap
	// naming what could not be checked. A confident, ungapped answer is wrong here.
	ExpectCaveatedExplanation
	// ExpectAbstention means no explanation is sufficiently supported and declining to answer is
	// the correct behaviour. A confident explanation is a failure of the standard, not a bonus.
	ExpectAbstention
)

func (e Expectation) String() string {
	switch e {
	case ExpectExplanation:
		return "a supported explanation"
	case ExpectCaveatedExplanation:
		return "an explanation caveated by a coverage gap, or an abstention"
	case ExpectAbstention:
		return "an abstention naming what could not be checked"
	default:
		return "unrecognised"
	}
}

// GroundTruth is the cause, written down first.
//
// It never appears in the artifact a scorer reads. It is joined afterwards, because a scorer who
// knows the answer grades recognition rather than reasoning.
type GroundTruth struct {
	// Cause is what is actually wrong, in one sentence.
	Cause string
	// Decisive is the evidence a senior engineer would consider decisive. It is what "did it
	// choose the evidence a senior engineer would have chosen" is compared against.
	Decisive []string
	// Expected is what a correct terminal outcome looks like.
	Expected Expectation
	// Note says why this scenario is in the set. The set is chosen, not sampled, and the reason
	// each member is here is part of what the instrument's limits have to state out loud.
	Note string
}

// Scenario is one broken cluster, everything needed to build it, and the proof it was built.
type Scenario struct {
	// ID is stable and is what a run is filed under. It never changes for a scenario, because
	// comparing two runs of "the same scenario" across a planner change is the whole point.
	ID    string
	Title string

	Namespace string
	// Workload is what the investigation is scoped to, and Kind is what it is.
	//
	// StatefulSet is the default kind across this set, and deliberately so: its pod is
	// deterministically <name>-0, so a recorded transcript that proposes reading a pod's log
	// stays valid across runs. A Deployment's pod name is generated by the cluster, which would
	// make every recording single-use.
	Workload string
	Kind     string

	// Window is how far back the investigation looks. It is per scenario because one of them is
	// about a window reaching past what the source can answer for.
	Window time.Duration

	// RelayEnvironment is extra configuration for the Relay serving this scenario. Only the
	// expired-evidence scenario uses it, and what it sets there is an operator attestation about
	// the cluster rather than a switch on the product.
	RelayEnvironment map[string]string

	// Provision creates the broken state. It returns once everything has been submitted; whether
	// the cluster ACTUALLY reached the state is Ready's question, not this one's.
	Provision func(ctx context.Context, client kubernetes.Interface) error

	// Ready proves the cluster reached the declared broken state. A scenario whose readiness
	// condition does not hold is discarded rather than scored.
	//
	// It is declared per scenario rather than derived, because "broken" means something different
	// in each: a pod that cannot pull an image, a container the kernel killed, a pod nothing will
	// schedule. A generic "not healthy" check would pass for the wrong failure.
	Ready func(ctx context.Context, client kubernetes.Interface) error

	Truth GroundTruth
}

// ErrNotProvisioned reports a cluster that did not reach the scenario's declared broken state.
// The run is discarded on it; nothing is scored.
var ErrNotProvisioned = fmt.Errorf("the cluster did not reach the scenario's declared state")

// Prepare builds the scenario's namespace, provisions it, and waits for its readiness condition.
func (s Scenario) Prepare(ctx context.Context, client kubernetes.Interface) error {
	prepareCtx, cancel := context.WithTimeout(ctx, provisionTimeout)
	defer cancel()

	_, err := client.CoreV1().Namespaces().Create(prepareCtx,
		&corev1.Namespace{ObjectMeta: metav1.ObjectMeta{Name: s.Namespace}},
		metav1.CreateOptions{})
	if err != nil {
		return fmt.Errorf("scenario %s: creating namespace %s: %w", s.ID, s.Namespace, err)
	}

	if err = s.Provision(prepareCtx, client); err != nil {
		return fmt.Errorf("scenario %s: provisioning: %w", s.ID, err)
	}
	if err = s.Ready(prepareCtx, client); err != nil {
		return fmt.Errorf("%w: scenario %s: %w", ErrNotProvisioned, s.ID, err)
	}
	return nil
}

// awaitPod polls one pod until the condition holds, and says what it was waiting for when it
// does not. The description is the readiness condition in words, so a discarded run names the
// state the cluster failed to reach rather than reporting a timeout.
func awaitPod(
	ctx context.Context, client kubernetes.Interface, namespace, selector, description string,
	holds func(pod *corev1.Pod) bool,
) error {
	var last string
	for {
		pods, err := client.CoreV1().Pods(namespace).List(ctx, metav1.ListOptions{
			LabelSelector: selector, Limit: 10,
		})
		if err == nil {
			for i := range pods.Items {
				if holds(&pods.Items[i]) {
					return nil
				}
			}
			last = describePods(pods.Items)
		} else {
			last = err.Error()
		}

		select {
		case <-ctx.Done():
			return fmt.Errorf("waited for %s and it did not happen; the cluster reports %s",
				description, last)
		case <-time.After(readinessPoll):
		}
	}
}

// describePods renders what the cluster currently says, so a discarded run carries the evidence
// for why it was discarded rather than only the fact.
func describePods(pods []corev1.Pod) string {
	if len(pods) == 0 {
		return "no pods"
	}
	described := ""
	for i := range pods {
		pod := &pods[i]
		described += fmt.Sprintf("[%s phase=%s", pod.Name, pod.Status.Phase)
		for _, status := range pod.Status.ContainerStatuses {
			described += fmt.Sprintf(" %s ready=%t restarts=%d",
				status.Name, status.Ready, status.RestartCount)
			if waiting := status.State.Waiting; waiting != nil {
				described += " waiting=" + waiting.Reason
			}
			if terminated := status.LastTerminationState.Terminated; terminated != nil {
				described += fmt.Sprintf(" lastExit=%d(%s)",
					terminated.ExitCode, terminated.Reason)
			}
		}
		for _, condition := range pod.Status.Conditions {
			if condition.Type == corev1.PodScheduled && condition.Status == corev1.ConditionFalse {
				described += " unschedulable=" + condition.Reason
			}
		}
		described += "]"
	}
	return described
}

// waitingReason reports a container's waiting reason, which is how the cluster says "this could
// not start" and why.
func waitingReason(pod *corev1.Pod) string {
	for _, status := range pod.Status.ContainerStatuses {
		if waiting := status.State.Waiting; waiting != nil {
			return waiting.Reason
		}
	}
	return ""
}

// restartedWith reports whether a container has died at least once with this termination reason,
// which is what makes a previous-container log read possible and what "the kernel killed it"
// looks like from outside.
func restartedWith(pod *corev1.Pod, reason string) bool {
	for _, status := range pod.Status.ContainerStatuses {
		terminated := status.LastTerminationState.Terminated
		if terminated == nil || status.RestartCount < 1 {
			continue
		}
		if reason == "" || terminated.Reason == reason {
			return true
		}
	}
	return false
}

// runningButNotReady is a workload that started and never became usable — the shape a failing
// readiness probe produces, and the one where the cluster's own account says least.
func runningButNotReady(pod *corev1.Pod) bool {
	if pod.Status.Phase != corev1.PodRunning {
		return false
	}
	for _, status := range pod.Status.ContainerStatuses {
		if status.Ready {
			return false
		}
	}
	return len(pod.Status.ContainerStatuses) > 0
}

// containerNeverCreated is the shape a pod takes when the kubelet could not build the container
// at all — a Secret or ConfigMap it references is not there. Two scenarios end here and both
// depend on the same pair of reasons, so the pair is named once.
func containerNeverCreated(pod *corev1.Pod) bool {
	reason := waitingReason(pod)
	return reason == "CreateContainerConfigError" || reason == "CreateContainerError"
}

// running is a pod that started, whatever it went on to do. It is what "the previous revision was
// fine" looks like before a scenario breaks it.
func running(pod *corev1.Pod) bool { return pod.Status.Phase == corev1.PodRunning }

// unschedulable is a pod no node will take. The answer is about the cluster rather than the
// workload, which is the distinction that scenario exists to test.
func unschedulable(pod *corev1.Pod) bool {
	for _, condition := range pod.Status.Conditions {
		if condition.Type == corev1.PodScheduled &&
			condition.Status == corev1.ConditionFalse &&
			condition.Reason == corev1.PodReasonUnschedulable {
			return true
		}
	}
	return false
}
