package e2e

import (
	"context"
	"fmt"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
)

// The workloads the scenarios are built from.
//
// Every scenario workload is a StatefulSet, and the reason is the recorded transcript. A
// StatefulSet's pod is deterministically <name>-0, so a recording that proposes reading that
// pod's log stays valid across runs; a Deployment's pod name is generated by the cluster, which
// would make every recording single-use and every comparison between two runs impossible.
//
// The images are the two already pinned by the protocol proof. Pinning rather than floating is
// what stops a base-image change quietly turning one scenario into a different one.

// scenarioContainer is the name every scenario's container carries. One name across the set means
// a transcript's container argument is the same in all of them, which is one fewer thing for a
// recording to be specific about.
const scenarioContainer = "app"

// podOf is the pod a scenario's workload has, knowable before the cluster creates it.
func podOf(workload string) string { return workload + "-0" }

// workload describes one scenario's StatefulSet.
type workload struct {
	name      string
	namespace string
	// shell is what the container runs. It is a fixture of this harness and nothing the product
	// can do: the Relay has no path that runs a command, which its own build-failing gates
	// enforce.
	shell string
	image string
	// memoryLimit, when set, is the container's memory ceiling — the lever the OOM scenario
	// pulls.
	memoryLimit string
	cpuRequest  string
	// probe, when set, is a readiness probe command. A workload that runs and never becomes
	// ready is a different failure from one that crashes, and this is what produces it.
	probe []string
	// secretRef, when set, names a Secret the container takes its environment from. A missing one
	// is why a container never starts.
	secretRef string
	// configMapRef, when set, mounts a ConfigMap the container reads its configuration from.
	configMapRef string
	// annotation lets a revision be changed without changing anything a reader would call a
	// cause, which is what makes an innocent recent change innocent.
	annotation string
}

// apply creates or replaces the workload.
func (w workload) apply(ctx context.Context, client kubernetes.Interface) error {
	sets := client.AppsV1().StatefulSets(w.namespace)
	desired := w.statefulSet()

	existing, err := sets.Get(ctx, w.name, metav1.GetOptions{})
	if err == nil {
		desired.ResourceVersion = existing.ResourceVersion
		if _, err = sets.Update(ctx, desired, metav1.UpdateOptions{}); err != nil {
			return fmt.Errorf("updating statefulset %s: %w", w.name, err)
		}
		return nil
	}
	if _, err = sets.Create(ctx, desired, metav1.CreateOptions{}); err != nil {
		return fmt.Errorf("creating statefulset %s: %w", w.name, err)
	}
	return nil
}

func (w workload) statefulSet() *appsv1.StatefulSet {
	labels := map[string]string{"app": w.name}
	image := w.image
	if image == "" {
		image = logImage
	}

	container := corev1.Container{
		Name:  scenarioContainer,
		Image: image,
	}
	if w.shell != "" {
		container.Command = []string{"sh", "-c", w.shell}
	}
	if w.memoryLimit != "" || w.cpuRequest != "" {
		container.Resources = corev1.ResourceRequirements{
			Limits:   corev1.ResourceList{},
			Requests: corev1.ResourceList{},
		}
		if w.memoryLimit != "" {
			container.Resources.Limits[corev1.ResourceMemory] = resource.MustParse(w.memoryLimit)
		}
		if w.cpuRequest != "" {
			container.Resources.Requests[corev1.ResourceCPU] = resource.MustParse(w.cpuRequest)
		}
	}
	if len(w.probe) > 0 {
		container.ReadinessProbe = &corev1.Probe{
			ProbeHandler: corev1.ProbeHandler{
				Exec: &corev1.ExecAction{Command: w.probe},
			},
			InitialDelaySeconds: 2,
			PeriodSeconds:       3,
			FailureThreshold:    1,
		}
	}
	if w.secretRef != "" {
		container.EnvFrom = append(container.EnvFrom, corev1.EnvFromSource{
			SecretRef: &corev1.SecretEnvSource{
				LocalObjectReference: corev1.LocalObjectReference{Name: w.secretRef},
			},
		})
	}

	template := corev1.PodTemplateSpec{
		ObjectMeta: metav1.ObjectMeta{Labels: labels},
		Spec: corev1.PodSpec{
			Containers: []corev1.Container{container},
			// Nothing here waits politely. A scenario is a broken cluster and the harness needs it
			// broken quickly; a graceful period would only delay the state being observable.
			TerminationGracePeriodSeconds: ptr(int64(1)),
		},
	}
	if w.configMapRef != "" {
		template.Spec.Volumes = []corev1.Volume{{
			Name: "configuration",
			VolumeSource: corev1.VolumeSource{
				ConfigMap: &corev1.ConfigMapVolumeSource{
					LocalObjectReference: corev1.LocalObjectReference{Name: w.configMapRef},
				},
			},
		}}
		template.Spec.Containers[0].VolumeMounts = []corev1.VolumeMount{{
			Name: "configuration", MountPath: "/etc/app", ReadOnly: true,
		}}
	}
	if w.annotation != "" {
		template.Annotations = map[string]string{"scenario.opencluster/revision": w.annotation}
	}

	return &appsv1.StatefulSet{
		ObjectMeta: metav1.ObjectMeta{Name: w.name, Namespace: w.namespace, Labels: labels},
		Spec: appsv1.StatefulSetSpec{
			Replicas:    ptr(int32(1)),
			ServiceName: w.name,
			Selector:    &metav1.LabelSelector{MatchLabels: labels},
			Template:    template,
		},
	}
}

// selectorFor is the label selector a scenario's pods carry.
func selectorFor(workload string) string { return "app=" + workload }

// putConfigMap creates or replaces a ConfigMap.
func putConfigMap(
	ctx context.Context, client kubernetes.Interface, namespace, name string,
	data map[string]string,
) error {
	maps := client.CoreV1().ConfigMaps(namespace)
	desired := &corev1.ConfigMap{
		ObjectMeta: metav1.ObjectMeta{Name: name, Namespace: namespace},
		Data:       data,
	}

	existing, err := maps.Get(ctx, name, metav1.GetOptions{})
	if err == nil {
		desired.ResourceVersion = existing.ResourceVersion
		if _, err = maps.Update(ctx, desired, metav1.UpdateOptions{}); err != nil {
			return fmt.Errorf("updating configmap %s: %w", name, err)
		}
		return nil
	}
	if _, err = maps.Create(ctx, desired, metav1.CreateOptions{}); err != nil {
		return fmt.Errorf("creating configmap %s: %w", name, err)
	}
	return nil
}
